default: &default
  adapter: postgresql
  encoding: unicode
# UNCOMMENT THESE 3 LINES TO BUILD DOCKER CONTAINER PROPERLY
  # host: db
  # username: postgres
  # password:
# UNCOMMENT THESE 3 LINES TO BUILD DOCKER CONTAINER PROPERLY
  pool: 5

development:
  <<: *default
  database: auxilio-api-server_development


test:
  <<: *default
  database: auxilio-api-server_test